import * as fs from 'fs';
import * as path from 'path';
import { extractEntity, classifyDuring } from './adapters/resolve';
import { parseOtherLanguages } from './fandomClient';
import { parseInfobox } from './adapters/parse';
const CACHE = path.resolve(__dirname, '.cache');
const ds = JSON.parse(fs.readFileSync(path.resolve(__dirname,'out/music-source-dataset.json'),'utf8'));
const cacheByTitle = new Map<string, {title:string;wt:string;redirects:any[]}>();
for(const f of fs.readdirSync(CACHE).filter(x=>x.endsWith('.json'))){let d:any;try{d=JSON.parse(fs.readFileSync(path.join(CACHE,f),'utf8'));}catch{continue;}const p=d?.parse;if(!p||!p.title)continue;cacheByTitle.set(p.title.toLowerCase(),{title:p.title,wt:p.wikitext?.['*']||'',redirects:p.redirects||[]});}
function isSound(t:string,w:string){return /soundtrack/i.test(t)||/{{Soundtrack Infobox/i.test(w);}
function findC(e:string){const en=e.trim();const d=cacheByTitle.get(en.toLowerCase());if(d)return{title:d.title,wt:d.wt};for(const v of cacheByTitle.values())for(const r of v.redirects)if(r?.from&&r.from.toLowerCase()===en.toLowerCase())return{title:v.title,wt:v.wt};const norm=(s:string)=>s.toLowerCase().replace(/[\s_/]+/g,' ').trim();for(const v of cacheByTitle.values())if(norm(v.title)===norm(en)&&!isSound(v.title,v.wt))return{title:v.title,wt:v.wt};let fb:any=null;for(const v of cacheByTitle.values())if(v.title.toLowerCase().includes(en.toLowerCase())&&!isSound(v.title,v.wt)){if(!fb)fb=v;}return fb?{title:fb.title,wt:fb.wt}:null;}
function readP(t:string,w:string){if(isSound(t,w))return null;const ns=['Mission Infobox','Location Infobox','Area Infobox','Zone Infobox','Mission','Location','Area','Zone'];let ib:any=null;for(const n of ns){ib=parseInfobox(w,n);if(ib&&Object.keys(ib).length)break;}if(ib)for(const f of ['location','area','subarea','region','zone','world','planet','system']){const v=ib[f];if(!v)continue;const c=v.replace(/\[\[(?:[^|\]]*\|)?([^\]]+)\]\]/g,'$1').replace(/\s*\((Location|Area|Region|Zone|Disambiguation|Mission)\)/gi,'').replace(/'''?/g,'').trim();if(c&&c.toLowerCase()!==t.toLowerCase())return c;}return null;}
function trS(s:string){const c=findC(s);if(!c)return s;const ol=parseOtherLanguages(c.wt);return ol.zhs||ol.zh||ol.zht||s;}
async function resolveOffline(raw:string){const kind=classifyDuring(raw) as any;const e=extractEntity(raw,kind);if(!e)return{zh:[],resolved:false};const chain:string[]=[];const vis=new Set<string>();let cur:string|null=e;let d=0;let hp=false;while(cur&&d<6){const k=cur.toLowerCase();if(vis.has(k))break;vis.add(k);chain.unshift(cur);const c=findC(cur);if(!c)break;if(d===0&&isSound(c.title,c.wt))return{zh:[],resolved:false};const p=readP(c.title,c.wt);if(p&&d===0)hp=true;cur=p;d++;}return{zh:chain.map(trS),resolved:chain.length>0,hasParent:hp};}
const trackCn=new Set<string>();for(const t of (ds.genshin?.tracks||[]))if(t.trackTitle)trackCn.add(t.trackTitle);
async function main(){let oldSong=0,newSong=0,checked=0;const samp:string[]=[];for(const e of (ds.genshin?.tracks||[])){for(const loc of (e.locations||[])){const raw=loc.raw||'';if(!raw)continue;const before=loc.zhPath||[];const bS=before.some((s:string)=>trackCn.has(s));const after=await resolveOffline(raw);const aS=(after.zh||[]).some((s:string)=>trackCn.has(s));checked++;if(bS)oldSong++;if(aS){newSong++;if(samp.length<8)samp.push(`  ${e.trackTitle||e.pageTitle}: raw="${String(raw).slice(0,50)}" OLD[${before.join('/')}] NEW[${after.zh.join('/')}]`);}}}console.log('=== Genshin offline hardened replay ===');console.log('locations:',checked,'OLD song misplant:',oldSong,'NEW:',newSong);if(samp.length){console.log('NEW song hits:');console.log(samp.join('\n'));}}
main().catch(e=>{console.error(e);process.exit(1);});
